--TẠO VIEW

USE QLBongDa;
go

CREATE VIEW vCau1 AS
SELECT CAUTHU.MACT, CAUTHU.HOTEN, CAUTHU.NGAYSINH, CAUTHU.DIACHI, CAUTHU.VITRI
FROM CAUTHU
JOIN CAULACBO ON CAUTHU.MACLB = CAULACBO.MACLB
JOIN QUOCGIA ON CAUTHU.MAQG = QUOCGIA.MAQG
WHERE CAULACBO.TENCLB = N'SHB Đà Nẵng' AND QUOCGIA.TENQG = 'Brazil'

go
select * from vCau1
go

CREATE VIEW vCau2 AS
SELECT TRANDAU.MATRAN, TRANDAU.NGAYTD, SANVD.TENSAN, clb1.TenCLB AS TenCLB1, clb2.TENCLB AS TENCLB2, TRANDAU.KETQUA
FROM TRANDAU
JOIN SANVD ON TRANDAU.MASAN = SANVD.MASAN 
JOIN CAULACBO clb1 ON clb1.MaCLB = TRANDAU.MACLB1 
JOIN CAULACBO clb2 ON clb2.MaCLB = TRANDAU.MACLB2 
WHERE TRANDAU.NAM = 2009 AND TRANDAU.VONG = 3;

go
select * from vCau2
go

CREATE VIEW vCau3 AS
SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HLVCLB.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN HLV
INNER JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
INNER JOIN HLV_CLB HLVCLB ON HLV.MAHLV = HLVCLB.MAHLV
INNER JOIN CAULACBO CLB ON HLVCLB.MACLB = CLB.MACLB
WHERE QG.TENQG = N'Việt Nam';

go
select * from vCau3
go

 CREATE VIEW vCau4 AS
 SELECT CLB.MACLB, CLB.TENCLB, SANVD.TENSAN, SANVD.DIACHI, COUNT(DISTINCT CT.MACT) AS SOCAUTHUNN
 FROM CAUTHU CT
 INNER JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
 INNER JOIN SANVD ON CLB.MASAN = SANVD.MASAN
 WHERE CT.MAQG <> 'VN'
 GROUP BY CLB.MACLB, CLB.TENCLB, SANVD.TENSAN, SANVD.DIACHI
 HAVING COUNT(DISTINCT CT.MACT) > 2;

go
select * from vCau4
go

CREATE VIEW vCau5 AS
SELECT T.TENTINH, COUNT(DISTINCT CT.MACT) AS SLTIENDAO
FROM CAUTHU CT
INNER JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
INNER JOIN TINH T ON CLB.MATINH = T.MATINH
WHERE CT.VITRI = N'Tiền đạo'
GROUP BY T.TENTINH

go
select * from vCau5
go

CREATE VIEW vCau6 AS
SELECT TOP 1 CLB.TENCLB, T.TENTINH
FROM BANGXH BXH
INNER JOIN CAULACBO CLB ON BXH.MACLB = CLB.MACLB
INNER JOIN TINH T ON CLB.MATINH = T.MATINH
WHERE BXH.VONG = 3 AND BXH.NAM = 2009
ORDER BY BXH.HANG DESC

go
select * from vCau6
go

CREATE VIEW vCau7 AS
SELECT HLV.TENHLV
FROM HUANLUYENVIEN HLV
INNER JOIN HLV_CLB HLVCLB ON HLV.MAHLV = HLVCLB.MAHLV
INNER JOIN CAULACBO CLB ON HLVCLB.MACLB = CLB.MACLB
WHERE HLV.DIENTHOAI IS NULL

go
select * from vCau7
go

CREATE VIEW vCau8 AS
SELECT HLV.TENHLV
FROM HUANLUYENVIEN HLV
LEFT JOIN HLV_CLB HLVCLB ON HLV.MAHLV = HLVCLB.MAHLV
LEFT JOIN CAULACBO CLB ON HLVCLB.MACLB = CLB.MACLB
WHERE HLVCLB.VAITRO IS NULL AND HLV.MAQG = 'VN' AND CLB.MACLB IS NULL

go
select * from vCau8
go


CREATE VIEW vCau9 AS
SELECT td.NGAYTD, svd.TENSAN, clb1.TENCLB AS TENCLB1, clb2.TENCLB AS TENCLB2, td.KETQUA
FROM TRANDAU td
INNER JOIN SANVD svd ON td.MASAN = svd.MASAN
LEFT JOIN CAULACBO clb1 ON td.MACLB1 = clb1.MACLB
LEFT JOIN CAULACBO clb2 ON td.MACLB2 = clb2.MACLB
WHERE td.VONG <=3 AND td.NAM = 2009
AND clb1.MACLB IN (
    SELECT TOP 1  MACLB FROM BANGXH WHERE NAM = 2009 AND VONG <= 3 ORDER BY DIEM DESC)
OR  clb2.MACLB IN (
	SELECT TOP 1  MACLB FROM BANGXH WHERE NAM = 2009 AND VONG <= 3 ORDER BY DIEM DESC)

go
select * from vCau9
go



CREATE VIEW vCau10 AS
SELECT td.NGAYTD, svd.TENSAN, clb1.TENCLB AS TENCLB1, clb2.TENCLB AS TENCLB2, td.KETQUA
FROM TRANDAU td
INNER JOIN SANVD svd ON td.MASAN = svd.MASAN
LEFT JOIN CAULACBO clb1 ON td.MACLB1 = clb1.MACLB
LEFT JOIN CAULACBO clb2 ON td.MACLB2 = clb2.MACLB
WHERE td.VONG = 3 AND td.NAM = 2009
AND clb1.MACLB IN (
    SELECT TOP 1  MACLB FROM BANGXH WHERE NAM = 2009 AND VONG = 3 ORDER BY DIEM ASC)
OR  clb2.MACLB IN (
	SELECT TOP 1  MACLB FROM BANGXH WHERE NAM = 2009 AND VONG = 3 ORDER BY DIEM ASC)

go
select * from vCau10
go