--PHÂN QUY?N
----T?o user và phân quy?n cho BDAdmin ðý?c toàn quy?n trên CSDL QLBongDa
CREATE LOGIN BDAdmin WITH PASSWORD = '1';
USE QLBongDa;
CREATE USER BDAdmin FOR LOGIN BDAdmin;
GO
ALTER ROLE db_owner ADD MEMBER BDAdmin;
GO

----T?o user và phân quy?n cho BDBK ðý?c phép backup CSDL QLBongDa
CREATE LOGIN BDBK WITH PASSWORD = '1';
USE QLBongDa;
CREATE USER BDBK FOR LOGIN BDBK;
GO
ALTER ROLE db_backupoperator ADD MEMBER BDBK;
GO

----T?o user và phân quy?n cho BDRead ch? ðý?c phép xem d? li?u trong CSDL QLBongDa
CREATE LOGIN BDRead WITH PASSWORD = '1';
USE QLBongDa;
CREATE USER BDRead FOR LOGIN BDRead;
GO
ALTER ROLE db_datareader ADD MEMBER BDRead;
GO

-- T?o user và phân quy?n cho BDProfile ðý?c phép thao tác SQL Profile
CREATE LOGIN BDProfile WITH PASSWORD = '1';
USE QLBongDa;
CREATE USER BDProfile FOR LOGIN BDProfile;
GO
ALTER ROLE db_datawriter ADD MEMBER BDProfile;
GO

----T?o user và phân quy?n cho BDU01 ðý?c phép thêm m?i table
CREATE LOGIN BDU01 WITH PASSWORD = '1';
CREATE USER BDU01 FOR LOGIN BDU01;

USE QLBongDa;
GO
CREATE SCHEMA [BDU01];
GO
GRANT CREATE TABLE TO [BDU01];
GO
ALTER AUTHORIZATION ON SCHEMA::[BDU01] TO [BDU01];
GO

----T?o user và phân quy?n cho BDU02 ðý?c phép c?p nh?t các table, 
--không ðý?c phép thêm m?i ho?c xóa table
CREATE LOGIN BDU02 WITH PASSWORD = '1';
CREATE USER BDU02 FOR LOGIN BDU02;
GRANT UPDATE ON SCHEMA::dbo TO BDU02;
DENY ALTER ON SCHEMA::dbo TO BDU02;
DENY CREATE TABLE TO BDU02;
DENY DELETE TO BDU02;

----T?o user và phân quy?n cho BDU03 ch? ðý?c phép thao tác table CauLacBo 
--(select, insert, delete, update), không ðý?c phép thao tác các table khác
CREATE LOGIN BDU03 WITH PASSWORD = '1';
CREATE USER BDU03 FOR LOGIN BDU03;
GRANT SELECT, INSERT,DELETE, UPDATE ON dbo.CAULACBO TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.BANGXH TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.CAUTHU TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.HLV_CLB TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.HUANLUYENVIEN TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.QUOCGIA TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.SANVD TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.TINH TO BDU03;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.TRANDAU TO BDU03;

----T?o user và phân quy?n cho BDU04 ch? ðý?c phép thao tác table CAUTHU:
--không ðý?c phép xem c?t Ngày sinh (NGAYSINH)
--Không ch?nh s?a giá tr? trong c?t V? trí (VITRI) 
--không ðý?c phép thao tác các table khác
CREATE LOGIN BDU04 WITH PASSWORD = '1';
CREATE USER BDU04 FOR LOGIN BDU04;
GRANT SELECT, INSERT, UPDATE, DELETE ON CAUTHU TO BDU04;
DENY SELECT ON CAUTHU(NGAYSINH) TO BDU04;
DENY UPDATE ON CAUTHU(VITRI) TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.BANGXH TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.CAULACBO TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.HLV_CLB TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.HUANLUYENVIEN TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.QUOCGIA TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.SANVD TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.TINH TO BDU04;
DENY SELECT, INSERT, DELETE, UPDATE ON dbo.TRANDAU TO BDU04;
